pipeline {
    agent any
    
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    
    stages {
        stage('git init') {
            steps {
                echo 'Git Init'
                git url: 'https://github.com/554452/spring-petclinic.git/',
                branch: 'main', credentialsId: 'gitCredentals'
            }
        }
    
        stage('Bulid') {
            steps {
                echo 'Bulid'
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'            
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
    
}
