pipeline {
    agent any

    tools {
        maven "M3"
        jdk "JDK11"
    }

    stages {
        stage('Git Clone') {
            steps{
            echo 'Git Clone'
            git url: 'https://github.com/554452/spring-petclinic.git',
            branch : 'main', credentialsId: 'gitCredentials'
            }
            post {
                success {
                    echo 'Git Clone success'
            }
                failure {
                    echo 'Git Clone Fail'
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Docker image') {
            steps {
            echo 'Dokcer Image'
            }
        }
        stage('Docker Push') {
            steps {
        echo 'Docker Push'
            }
        }    
        stage('Target Pull') {
            steps {
            echo 'Target Pull'
            }
        }
    }
}
